function dz = construct_data(z,coe,coupling_mat) 
    dz = coe(1) + coe(2).*z + coe(3).*conj(z) + coe(4).*(z.*z)...
        + coe(5).*(z.*conj(z)) + coe(6).*(conj(z.*z)) + coe(7).*(z.*z.*z)...
        + coe(8).*(z.*z.*conj(z)) + coe(9).*(z.*(conj(z.*z))) +coe(10).*(conj(z.*z.*z))...
        + (coupling_mat).*z;
end